### ISSUE TITLE
No chat notifications when drift chat page is dismissed replies not loading

### ISSUE THREAD

**Issue by vamsivannam** [Driftt/drift-sdk-ios#70]
No chat notifications when drift chat page is dismissed and replies are not appearing on chat view unless navigated back to chat list

**Comment by eoinoconnell** [comment]
Hi, Sorry for the delay. I haven't been able to reproduce this on my side. 

Could you clarify the issue with steps to reproduce it?

**Comment by bradenboothby** [comment]
i have the same issue

**Comment by eoinoconnell** [comment]
Hi @bradenboothby, thanks for the report, do you have any more information on this issue and how you are reproducing it?

**Comment by eoinoconnell** [comment]
This should now be resolved in version 2.2.7 which is now on cocoapods

**Comment by bradenboothby** [comment]
I have updated through cocoapods, and I still have the same issue

**Comment by eoinoconnell** [comment]
Hi @bradenboothby, can you provide steps in order to reproduce this?
